In [1]:
import pandas as pd
df = pd.read_csv("iris.csv")
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [7]:
df['flowers'] = df['Species']
df.drop(['Species'],axis=1, inplace=True)
df.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      flowers
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [19]:
X=df.drop(['flowers'],axis=1,)
y = df['flowers']

In [20]:
from sklearn.model_selection import train_test_split

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state = 0)

In [26]:
X_train.shape

(105, 5)

In [28]:
from sklearn import svm, datasets

In [30]:
model = svm.SVC(kernel='rbf',gamma='auto',C=30)
model.fit(X_train,y_train)
model.score(X_test,y_test)

1.0

In [43]:
from sklearn.model_selection import cross_val_score
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'), X, y, cv=5)

array([0.66666667, 1.        , 1.        , 1.        , 0.7       ])

In [44]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),X,y,cv=5)

array([0.46666667, 0.73333333, 0.73333333, 0.73333333, 0.53333333])

In [45]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),X,y,cv=5)

array([0.46666667, 0.73333333, 0.73333333, 0.73333333, 0.53333333])

## Another approach/way of doing cross_val_score 

In [63]:
import numpy as np
kernels = ['rbf','linear']
C = [1,10,20]
avg_score = {}
for knal in kernels:
    for cnal in C:
        cv_score=cross_val_score(svm.SVC(kernel=knal, C=cnal, gamma = 'auto'),X,y, cv=5)
        avg_score[knal + '_' + str(cnal)]=np.average(cv_score)

avg_score

{'rbf_1': 0.6399999999999999,
 'rbf_10': 0.6399999999999999,
 'rbf_20': 0.6399999999999999,
 'linear_1': 0.8733333333333333,
 'linear_10': 0.8733333333333333,
 'linear_20': 0.8733333333333333}

## Above methods is complicated in using Cross_val 
So we can use GridSearchCV for minimize the complixity of the code 

In [65]:
from sklearn.model_selection import GridSearchCV
clf = GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False)
clf.fit(X,y)
clf.cv_results_

{'mean_fit_time': array([0.01671987, 0.00687909, 0.00937133, 0.00121026, 0.01131754,
        0.00786419]),
 'std_fit_time': array([0.01645737, 0.00765102, 0.0076517 , 0.00242052, 0.00951436,
        0.00698861]),
 'mean_score_time': array([0.004388  , 0.00110893, 0.        , 0.00334001, 0.00020866,
        0.        ]),
 'std_score_time': array([0.00629285, 0.00157234, 0.        , 0.00619081, 0.00041733,
        0.        ]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value='?',
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
  {'C': 20, 'kernel': 'linear'}],


In [67]:
rf = pd.DataFrame(clf.cv_results_)
rf.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.016720      0.016457         0.004388        0.006293       1   
1       0.006879      0.007651         0.001109        0.001572       1   
2       0.009371      0.007652         0.000000        0.000000      10   
3       0.001210      0.002421         0.003340        0.006191      10   
4       0.011318      0.009514         0.000209        0.000417      20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.466667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.666667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.466667   
3       linear  {'C': 10, 'kernel': 'linear'}           0.666667   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.466667   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.733333           0.733333           0.733333           0.533333   
1           1.000000           1.000000           1.000000           0.700000   
2           0.733333           0.733333           0.733333           0.533333   
3           1.000000           1.000000           1.000000           0.700000   
4           0.733333           0.733333           0.733333           0.533333   

   mean_test_score  std_test_score  rank_test_score  
0         0.640000        0.116237                4  
1         0.873333        0.155492                1  
2         0.640000        0.116237                4  
3         0.873333        0.155492                1  
4         0.640000        0.116237                4

In [68]:
rf[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1          rbf         0.640000
1       1       linear         0.873333
2      10          rbf         0.640000
3      10       linear         0.873333
4      20          rbf         0.640000
5      20       linear         0.873333

In [70]:
clf.best_score_

0.8733333333333333

In [72]:
clf.best_params_

{'C': 1, 'kernel': 'linear'}

## Randomized SearchCV
It is better method to use cross_val than GridSearch because in randomized search we are able to choose how many iter(iteration)we want use then it gives us best output

In [74]:
from sklearn.model_selection import RandomizedSearchCV
reg = RandomizedSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
    
    },cv=5,                 
       return_train_score=False,
       n_iter=2)                 
reg.fit(X,y)

RandomizedSearchCV(cv=5, estimator=SVC(gamma='auto'), n_iter=2,
                   param_distributions={'C': [1, 10, 20],
                                        'kernel': ['rbf', 'linear']})

In [75]:
rf = pd.DataFrame(reg.cv_results_)
rf.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.007463      0.004980         0.003318        0.001768       linear   
1       0.006366      0.008921         0.003925        0.006056          rbf   

  param_C                        params  split0_test_score  split1_test_score  \
0       1  {'kernel': 'linear', 'C': 1}           0.666667           1.000000   
1      10    {'kernel': 'rbf', 'C': 10}           0.466667           0.733333   

   split2_test_score  split3_test_score  split4_test_score  mean_test_score  \
0           1.000000           1.000000           0.700000         0.873333   
1           0.733333           0.733333           0.533333         0.640000   

   std_test_score  rank_test_score  
0        0.155492                1  
1        0.116237                2

In [76]:
rf[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0       1       linear         0.873333
1      10          rbf         0.640000

## Now we perform hyperparameter tuning

In [78]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression

model_param = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10]
        }
    }
}

In [79]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X,y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                   best_params
0                  svm    0.873333  {'C': 1, 'kernel': 'linear'}
1        random_forest    0.966667           {'n_estimators': 5}
2  logistic_regression    0.933333                     {'C': 10}

In [80]:
from sklearn import svm
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB
from sklearn.tree import DecisionTreeClassifier

In [82]:
model_params = {
    'svm': {
        'model': svm.SVC(gamma='auto'),
        'params' : {
            'C': [1,10,20,20,50],
            'kernel': ['rbf','linear']
        }  
    },
    'random_forest': {
        'model': RandomForestClassifier(),
        'params' : {
            'n_estimators': [1,5,10,20,50]
        }
    },
    'logistic_regression' : {
        'model': LogisticRegression(solver='liblinear',multi_class='auto'),
        'params': {
            'C': [1,5,10,20,50]
        }
    },
    'gaussianNB':{
        'model': GaussianNB(),
        'params':{
            'var_smoothing':[1,5,10,20,50]
        }
    },
    'multinomialNB':{
        'model': MultinomialNB(alpha=1.0, fit_prior=True),
        'params':{
            'alpha':[1,5,10,20,50]
        }
    },
    'decisiontreeclassifier':{
        'model': DecisionTreeClassifier(criterion='gini', splitter='best', max_depth=None, min_samples_split=2, min_samples_leaf=1),
        'params':{
            
        }
    }
}

In [83]:
scores = []

for model_name, mp in model_params.items():
    clf =  GridSearchCV(mp['model'], mp['params'], cv=5, return_train_score=False)
    clf.fit(X,y)
    scores.append({
        'model': model_name,
        'best_score': clf.best_score_,
        'best_params': clf.best_params_
    })
    
df = pd.DataFrame(scores,columns=['model','best_score','best_params'])
df

model  best_score                   best_params
0                     svm    0.873333  {'C': 1, 'kernel': 'linear'}
1           random_forest    0.973333          {'n_estimators': 50}
2     logistic_regression    0.953333                     {'C': 50}
3              gaussianNB    0.866667          {'var_smoothing': 1}
4           multinomialNB    0.773333                  {'alpha': 1}
5  decisiontreeclassifier    0.900000                            {}