In [20]:
import numpy as np

In [21]:
a = np.array([1,2,3],dtype='int32')
print(a)

[1 2 3]


In [22]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [23]:
#Get Dimension
a.ndim

1

In [24]:
b.shape

(2, 3)

In [25]:
#Get Type 
b.dtype

dtype('float64')

In [28]:
#Get Size
a.itemsize

8

In [38]:
#Get total size
a.nbytes

56

# Accessing/Changing specific element, rows, columns, etc

In [63]:
a = np.array([[1,2,3,4,5,6,7],
              [8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [34]:
#Get a specific element
a[1,5]

13

In [35]:
#get a specific Row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [36]:
#Get a specific columns
a[:,2]

array([ 3, 10])

In [59]:
#Get a little more fancy [startindex:endindex:stepsize]
#0 means first row, 1 and 6 means starts from 1 and ends with 6
#with printing every 2nd numbers
a[0,1:6:2]

array([2, 4, 6])

In [64]:
a[1,5]=20
print(a)

a[:,2] = 5
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


*3-d example

In [68]:
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [71]:
#Get specific element (work outside in)
b[0,1,1]

4

In [75]:
#replace
b[:,1,:] =  [[9,9],[8,8]]

In [73]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initilizing Different Types Of Array

In [79]:
#All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [80]:
#All 1s matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [86]:
#Any other numbers 
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [88]:
#Any others numbers (full_like)
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [95]:
#Random decimal numbers
#np.random.random_sample(a.shape)
np.random.rand(2,4)

array([[0.1862389 , 0.14109075, 0.20832519, 0.93681372],
       [0.17729678, 0.87815789, 0.89577186, 0.16716405]])

In [100]:
#Random Integer Value
np.random.randint(4,7,size = (3,3))

array([[5, 5, 5],
       [5, 5, 6],
       [6, 6, 4]])

In [101]:
#The identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [105]:
#repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,4,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [109]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9
print(z)

output[1:-1,1:-1] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### BE careful when copying arrays!!! 

In [114]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathematics

In [115]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [121]:
a+2

array([ 7,  8,  9, 10])

In [117]:
a-2

array([-1,  0,  1,  2])

In [118]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [123]:
b = np.array([1,0,1,0])
a+b

array([6, 6, 8, 8])

In [124]:
a ** 2

array([25, 36, 49, 64])

In [126]:
#Take a sign 
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

## Linear Algebra 

In [134]:
a = np.ones((2,3))
print(a)

b = np.full((3,2),2)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [137]:
#find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

#### statistics

In [138]:
stats = np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [141]:
np.min(stats,axis = 1)

array([1, 4])

In [142]:
np.max(stats,axis = 1)

array([3, 6])

In [145]:
np.sum(stats)

21

## Reorganizing

In [150]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

after = before.reshape((2,2,2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [156]:
#vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
               
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [161]:
#Horizontal
h1 = np.ones([2,4])
h2 = np.ones([2,2])
np.hstack((h1,h2))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

## Miscellaneous

### Load Data From File